services:
  myskills:
    container_name: myskills
    # Dockerfileを使用してイメージをビルドする設定はコメントアウトされているため、Docker Hubから最新のイメージをプルして使用する設定
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: mrmapleleaf/myskills:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
